name = "proxypool-worker"
main = "src/index.js"
compatibility_date = "2026-06-24"

[assets]
directory = "./public"
binding = "ASSETS"

[triggers]
crons = ["*/15 * * * *"]

[vars]
ADMIN_USERNAME = "admin"
WORKER_VALIDATE_MODE = "source"
CRON_FETCH_BATCH_SIZE = "3"
